"""
Phân tích xu hướng giá & phân khúc tiêu dùng - Dữ liệu Shopee đã làm sạch
Tác giả: (auto-generated by Claude)
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

DATA_PATH = "/mnt/user-data/outputs/Shopee_Cleaned_Data.csv"
OUT_DIR = "/mnt/user-data/outputs"

df = pd.read_csv(DATA_PATH)

# ============================================================
# 1. THỐNG KÊ MÔ TẢ GIÁ BÁN (gia_ban) VÀ GIÁ GỐC (gia_goc)
# ============================================================
desc = df[['gia_goc', 'gia_ban']].describe().T
desc['skew'] = df[['gia_goc', 'gia_ban']].skew()
desc['median'] = df[['gia_goc', 'gia_ban']].median()
print("=" * 70)
print("1. THỐNG KÊ MÔ TẢ GIÁ")
print("=" * 70)
print(desc)

discount_rate = (1 - df['gia_ban'] / df['gia_goc']) * 100
print(f"\nTỷ lệ giảm giá trung bình: {discount_rate.mean():.2f}%")
print(f"Số sản phẩm đang giảm giá (gia_ban < gia_goc): {(df['gia_ban'] < df['gia_goc']).sum():,} "
      f"({(df['gia_ban'] < df['gia_goc']).mean()*100:.1f}%)")

# ============================================================
# 2. PHÂN NHÓM GIÁ (theo gia_ban - giá khách hàng thực trả)
# ============================================================
bins   = [0, 10, 50, 100, 200, 500, 1000, np.inf]
labels = ['<10', '10-50', '50-100', '100-200', '200-500', '500-1000', '>1000']
df['nhom_gia'] = pd.cut(df['gia_ban'], bins=bins, labels=labels, right=False)

df['doanh_thu'] = df['gia_ban'] * df['luot_ban']

group = df.groupby('nhom_gia', observed=True).agg(
    so_san_pham   = ('ma_san_pham', 'count'),
    tong_luot_ban = ('luot_ban', 'sum'),
    doanh_thu     = ('doanh_thu', 'sum'),
    gia_tb        = ('gia_ban', 'mean'),
    danh_gia_tb   = ('diem_danh_gia', 'mean'),
).reset_index()

group['ty_trong_luot_ban_%']  = group['tong_luot_ban'] / group['tong_luot_ban'].sum() * 100
group['ty_trong_doanh_thu_%'] = group['doanh_thu']     / group['doanh_thu'].sum()     * 100
group['ty_trong_so_sp_%']     = group['so_san_pham']   / group['so_san_pham'].sum()   * 100
group = group.sort_values('nhom_gia')

print("\n" + "=" * 70)
print("2. TỔNG HỢP THEO NHÓM GIÁ")
print("=" * 70)
print(group.to_string(index=False))

group.to_csv(f"{OUT_DIR}/phan_tich_nhom_gia.csv", index=False)

# ============================================================
# 3. KẾT LUẬN NHANH: NHÓM GIÁ CHIẾM SỨC MUA CAO NHẤT
# ============================================================
top_sold_group    = group.loc[group['tong_luot_ban'].idxmax()]
top_revenue_group = group.loc[group['doanh_thu'].idxmax()]
print("\n" + "=" * 70)
print("3. KẾT LUẬN")
print("=" * 70)
print(f"- Nhóm giá có TỔNG LƯỢT BÁN cao nhất : {top_sold_group['nhom_gia']} "
      f"({top_sold_group['tong_luot_ban']:,.0f} lượt, chiếm {top_sold_group['ty_trong_luot_ban_%']:.1f}%)")
print(f"- Nhóm giá có DOANH THU cao nhất     : {top_revenue_group['nhom_gia']} "
      f"({top_revenue_group['doanh_thu']:,.0f}, chiếm {top_revenue_group['ty_trong_doanh_thu_%']:.1f}%)")

# ============================================================
# 4. TRỰC QUAN HÓA
# ============================================================
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 4.1 Phân phối giá bán (log scale vì lệch phải mạnh)
axes[0,0].hist(df['gia_ban'].clip(upper=df['gia_ban'].quantile(0.99)), bins=50, color='#4C9AFF')
axes[0,0].set_title('Phân phối giá bán (đã cắt tại percentile 99)')
axes[0,0].set_xlabel('Giá bán'); axes[0,0].set_ylabel('Số sản phẩm')

# 4.2 Tổng lượt bán theo nhóm giá
axes[0,1].bar(group['nhom_gia'].astype(str), group['tong_luot_ban'], color='#79D8B2')
axes[0,1].set_title('Tổng lượt bán theo nhóm giá')
axes[0,1].set_xlabel('Nhóm giá'); axes[0,1].set_ylabel('Tổng lượt bán')
axes[0,1].tick_params(axis='x', rotation=30)

# 4.3 Doanh thu theo nhóm giá
axes[1,0].bar(group['nhom_gia'].astype(str), group['doanh_thu'], color='#FF9999')
axes[1,0].set_title('Doanh thu theo nhóm giá')
axes[1,0].set_xlabel('Nhóm giá'); axes[1,0].set_ylabel('Doanh thu')
axes[1,0].tick_params(axis='x', rotation=30)

# 4.4 Tỷ trọng lượt bán vs tỷ trọng số sản phẩm (so sánh cung - cầu)
x = np.arange(len(group))
w = 0.35
axes[1,1].bar(x - w/2, group['ty_trong_so_sp_%'], width=w, label='% số sản phẩm', color='#AFC8E3')
axes[1,1].bar(x + w/2, group['ty_trong_luot_ban_%'], width=w, label='% lượt bán', color='#F4A261')
axes[1,1].set_xticks(x); axes[1,1].set_xticklabels(group['nhom_gia'].astype(str), rotation=30)
axes[1,1].set_title('So sánh tỷ trọng SỐ SẢN PHẨM vs LƯỢT BÁN')
axes[1,1].legend()

plt.tight_layout()
plt.savefig(f"{OUT_DIR}/phan_tich_gia_bieudo.png", dpi=150)
print(f"\nĐã lưu biểu đồ: {OUT_DIR}/phan_tich_gia_bieudo.png")
print(f"Đã lưu bảng tổng hợp: {OUT_DIR}/phan_tich_nhom_gia.csv")
